[package]
name = "gopher-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
url = "2.5"
tokio = { version = "1.41.1", features = ["full"] }

[lib]
name = "gopher_client"
path = "src/lib.rs"

[[bin]]
name = "gopher_client"
path = "src/main.rs"